title: Filippo Baudanza
logo: /assets/img/logo.png
email: bogus at gmail dot com
description: Minimalist is a theme powered by Jekyll. It is modified based on the Minimal theme.
show_downloads: false
#google_analytics: G-ZLK2GHB055
#remote_theme: BDHU/minimalist
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
 # - jekyll-remote-theme

# You can find fonts from https://iconify.design or https://fontawesome.com. Below is just an example illustrating how to use custom icons
sidebar:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/FilippoBau
  - name: Linkedin
    icon: <i class="fa-brands fa-linkedin"></i>
    link: www.linkedin.com/in/filippo-baudanza-3a62a1257
  - name: Blog
    icon: <i class="fa-solid fa-pen"></i>
    link: https://FilippoBau.github.io/blog/

# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
# When running locally, we run into the following error â€”
# GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
# adding this avoids it
github: [metadata]
